[phases.setup]
commands = [
  "pnpm dlx prisma generate",
  "pnpm dlx prisma migrate deploy"
]

[phases.install]
commands = [
  "npm install"
]

[phases.build]
commands = [
  "npm run build"
]

[start]
cmd = "source .env && node .output/server/index.mjs"
